// POSTS CONTEXT
export const GET_POSTS = 'GET_POSTS';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const FILTER_POSTS = 'FILTER_POSTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';

// USERS CONTEXT
export const GET_USERS = 'GET_USERS';
export const CLEAR_USERS = 'CLEAR_USERS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const FILTER_USERS = 'FILTER_USERS';
export const GET_CURRENT_USER_POSTS = 'GET_CURRENT_USER_POSTS';
