// POSTS CONTEXT
export const GET_POSTS = 'GET_POSTS';
export const GET_MORE_POSTS = 'GET_MORE_POSTS';
export const GET_CURRENT_USER_POSTS = 'GET_CURRENT_USER_POSTS';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const FILTER_POSTS = 'FILTER_POSTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
export const SINGLE_POST_CLEANUP = 'SINGLE_POST_CLEANUP';
export const CLEAR_ALL_POSTS = 'CLEAR_ALL_POSTS';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const SET_LOADING = 'SET_LOADING';

// USERS CONTEXT
export const GET_USERS = 'GET_USERS';
export const CLEAR_USERS = 'CLEAR_USERS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const FILTER_USERS = 'FILTER_USERS';
export const GET_SINGLE_USER = 'GET_SINGLE_USER';
export const CLEAR_SINGLE_USER = 'CLEAR_SINGLE_USER';

// NEWS CONTEXT
export const GET_ARTICLES = 'GET_ARTICLES';


